### ISSUE TITLE
nodejs-runtime does not work with catalogue

### ISSUE THREAD

**Issue by Trikolon** [reTHINK-project/dev-runtime-nodejs#21]
We'd like to deploy a hyperty using the nodejs-runtime and the catalogue for a demo. 

When I try to start the nodejs-runtime demo (npm run demo) with the FOKUS catalogue (catalogue.fokus.fraunhofer.de) it crashes.

Log from 'npm run demo':
https://gist.github.com/Trikolon/fe3bc79d27554d20a9051fdbf0b68a1c

My demo.js:
https://gist.github.com/Trikolon/a902337f7db9f58b16dfcc593009a39c

Tested on branch develop-constraints and on master.
The catalogue is running the latest version from https://github.com/reTHINK-project/dev-catalogue/ (master).

On Slack jboulmal told me that it would work with the hyperty-toolkit, why doesn't it work with the catalogue?

**Comment by pchainho** [comment]
It should work according to @luistduarte tests. Pls make sure you have nodejs ready Vertx protostub provisioned in your catalogue

**Comment by emmelmann-fokus** [comment]
If it doesn't work, maybe @Trikolon and @luistduarte can schedule an integration session to make it work.  We need a running installation to provision our hotel scenario demo permamently.

**Comment by jboulmal** [comment]
Hi @emmelmann-fokus,  As I said on slack  this error [[TypeError: runtimeFactory.createRuntimeCatalogue is not a function]](https://gist.github.com/Trikolon/fe3bc79d27554d20a9051fdbf0b68a1c#file-demo-run-log-L70), means you don't have the latest version of the runtime in develop branch.

**Comment by luistduarte** [comment]
Jboulmal is right, The runtime that you are using its from:   `Last build: Fri Nov 04 2016 16:46:19 GMT+0000`

**Comment by Trikolon** [comment]
Thanks for your feedback. I've added the nodejs-protostub and updated the runtime.
When I run the demo again I get this:
https://gist.github.com/Trikolon/77e660443486bc25e8a49e2a1c27b181
Which basically results in this error:  "Error while loading Hyperty, reason:  Response timeout!"

Is there a proper way to debug this and what would you suggest is the issue here?

**Comment by Trikolon** [comment]
^ Feedback appreciated.
Is there a docker-image for deployment of the catalogue with working components required for the nodejs-runtime? The nodejs-runtime has to not only work with the dev-toolkit but also the catalogue.

**Comment by jboulmal** [comment]
Hi @Trikolon 
As we said before is working fine with the toolkit, looking into the error logs, it's clear that you're requesting the default ProtoStub that's not compatible with runtime-Nodejs. Besides, if you take look at the toolkit  `develop` as I suggested many times in this thread, there is `VertxProtoStubNode`  for node.
Concerning docker-image, we will  upload it, but I don't think that's blocking issue right now.

**Comment by emmelmann-fokus** [comment]
Guys,  the goal is to have a deployable set-up which runs in the deployed components and *not* in the toolkit.

We need make progress here.  

@pchainho, do you think that @jboulmal and @Trikolon can arrange for a GoTo Meeting to discuss and *solve* this issue life.  I would suggest to include @Endebert as well to involve all people that developed related components.

@jboulmal : The missing docker image with a catalogue that allows to use the nodeJS runtime is a blocking issue for us now.  We need this to deploy our hotel use case "stand alone".

@Trikolon : please provide a detailed list of components that are required to deploy our scenario as a stand-alone, demonstrable use case.  So far I can identify that a step forward would be to have a docker image with a catalogue that against which the nodeJS runtime is tested and is running.  Please add additional components from our side.  Check them off if they are available.

**Comment by Trikolon** [comment]
@jboulmal I have deployed the nodejs protostub here: https://catalogue.fokus.fraunhofer.de/.well-known/protocolstub/NodejsProtoStub
It still tries to POST this though: ``` HTTPS Request: POST hyperty-catalogue://catalogue.fokus.fraunhofer.de/.well-known/protocolstub/default {"constraints":{"node":true}} ``` which lead to the VertxProtostub.
```
Mapped url is  https://catalogue.fokus.fraunhofer.de/.well-known/protocolstub/default method is: POST
statusCode is:  200
attaching raw sourcePackage from: hyperty-catalogue://catalogue.fokus.fraunhofer.de/.well-known/sourcepackage/VertxProtoStub
```

**Comment by jboulmal** [comment]
Hi @Trikolon  and @emmelmann-fokus, @pchainho  
Today, I have tried to run nodejs-runtime with latest develop branch of the toolkit. Unfortunately,  I'm getting errors on `nodejs-runtime`. Therefore, I have opened an  issue here  [Latest updates on develop throwing error on nodejs-runtime](https://github.com/reTHINK-project/dev-service-framework/issues/97).

**Comment by Trikolon** [comment]
@pchainho @jboulmal We have now updated the Runtime again with [the most current version from the runtime core dev branch](https://raw.githubusercontent.com/reTHINK-project/dev-runtime-core/develop/dist/Runtime.js).

There was a problem with printing an error which we fixed manually, but now we are stuck at some weird `hasOwnProperty` error: 

```
Error has occured while checking capability, reason: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at /home/pzu/reTHINK/repo/dev-runtime-nodejs/dist/RuntimeCapabilities.js:89:83
    at /home/pzu/reTHINK/repo/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:1346:23
    at callListener (/home/pzu/reTHINK/repo/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:1031:19)
    at endMicroTickScope (/home/pzu/reTHINK/repo/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:1118:25)
    at physicalTick (/home/pzu/reTHINK/repo/dev-runtime-nodejs/node_modules/dexie/dist/dexie.js:1093:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Error while loading Hyperty, reason:  Response timeout!
```

Here is the complete log as a gist: https://gist.github.com/Trikolon/d8bdfe984263d4b812a5b67a7969eec4

We've tried to fix it manually, but then we just get the response timeout without an error, so the problem might even be unrelated to this.

Could you give us advice on how to proceed? Are we using the wrong branch for the nodejs runtime (we are using `develop-constraint`)?

**Comment by jboulmal** [comment]
HI @Trikolon I confirm that I'm getting same error as you.
I tried with `toolkit` on `develop` branch, with all branches of `runtime-nodejs`.
These errors are independently of runtime-nodejs.
That's why I mentioned the issue in my previous comment.

**Comment by jboulmal** [comment]
Hi @Trikolon and @emmelmann-fokus,
This issue has been solved now.
Please try on `develop` branch of `runtime-nodejs`and we shall close this issue.

**Comment by Trikolon** [comment]
@jboulmal 
I've tried it on the latest state of branch develop now. It runs further but still fails. This is the error message:
```
Error: The config.url is a needed parameter
    at new VertxProtoStub (null:65:28)
    at Object.activate [as default] (null:324:15)
    at SandboxRegistry.process._registry._create (/home/pzu/reTHINK/repo/dev-runtime-nodejs/dist/ContextServiceProvider.js:63:30)
    at SandboxRegistry._onDeploy (eval at <anonymous> (/home/pzu/reTHINK/repo/dev-runtime-nodejs/node_modules/runtime-core/dist/sandbox.js:926:1), <anonymous>:124:51)
    at MsgListener.eval [as _callback] (eval at <anonymous> (/home/pzu/reTHINK/repo/dev-runtime-nodejs/node_modules/runtime-core/dist/sandbox.js:926:1), <anonymous>:76:17)
    at eval (eval at <anonymous> (/home/pzu/reTHINK/repo/dev-runtime-nodejs/node_modules/runtime-core/dist/minibus.js:721:1), <anonymous>:181:13)
    at Array.forEach (native)
    at MiniBus._publishOn (eval at <anonymous> (/home/pzu/reTHINK/repo/dev-runtime-nodejs/node_modules/runtime-core/dist/minibus.js:721:1), <anonymous>:180:16)
    at MiniBus._onMessage (eval at <anonymous> (/home/pzu/reTHINK/repo/dev-runtime-nodejs/node_modules/runtime-core/dist/minibus.js:768:1), <anonymous>:78:17)
    at process.<anonymous> (/home/pzu/reTHINK/repo/dev-runtime-nodejs/dist/ContextServiceProvider.js:49:20)
```
Which seems to result in
```
Error while loading Hyperty, reason:  Response timeout!
```

Full log file: https://gist.github.com/Trikolon/d8bdfe984263d4b812a5b67a7969eec4

**Comment by jboulmal** [comment]
Hi @Trikolon 
I have tried today, it's working fine.
Please update your `runtime, service-framework, etc`. on develop branch.
If the problem still persists get in touch with me on slack.

**Comment by Trikolon** [comment]
I've updated the Runtime and the Nodejs Protostub code in the catalogue with these versions:
Runtime: https://raw.githubusercontent.com/reTHINK-project/dev-runtime-core/develop/dist/Runtime.js
Protostub: https://raw.githubusercontent.com/reTHINK-project/dev-hyperty-toolkit/develop/resources/VertxProtoStubNode.js
Anything else I should update? If so, please point me to the files.

To me it looks like there is an issue with the VerxProtoStub constructor:
```
Error: The config.url is a needed parameter
    at new VertxProtoStub (null:65:28)
```
The error message remains. 

I suggest we keep the discussion here so everything is well documented and everyone can read / contribute.

**Comment by jboulmal** [comment]
@Trikolon 
the VertxProtoStub constructor is not of my competences. However, I have doubt about the way you build the ProtoStub in your catalogue.
If I'm to point you, I suggest to check here in [toolkit](https://github.com/reTHINK-project/dev-hyperty-toolkit/tree/develop/resources)

**Comment by Trikolon** [comment]
We've managed to resolve some deployment issues with the NodeJSProtostub which fixed the ```config.url is a needed parameter``` issue.
However, we still can't deploy the hyperty successfully:
```
Error while loading Hyperty, reason:  Response timeout!
```
There are no more specific error messages. Everything looks like it should work, but we get the response timeout again. We'd need more information to investigate futher.
Updated log: https://gist.github.com/Trikolon/d8bdfe984263d4b812a5b67a7969eec4

**Comment by Trikolon** [comment]
@jboulmal Do you know which component could cause the issue? Is it related to the Protostub? Do you know someone else who could have a look at this issue?

**Comment by jboulmal** [comment]
@Trikolon I think the ProtoStub has an issue.
If you can, Please join the #dev-runtime-nodejs channel on slack.
I don't have these issues.
I don't know why you still have them.

**Comment by emmelmann-fokus** [comment]
@Trikolon -- please update this issue with the current status.

@Trikolon @jboulmal @Endebert -- please arrange for a telco with screen sharing capabilities to have a remote integration meeting on this issue.  Please invite me to this meeting as well.

@pchainho can we have a short phone call to discuss on how the two of us can further assist the team to progress on this issue.

**Comment by Trikolon** [comment]
Update:
Previously the domain contacted by the nodejs-runtime was hard-coded to 'localhost' and therefore not compatible with usage of the catalogue (as an external component with custom url). This was likely due to development with the hyperty-toolkit (running on localhost). After discussing the issue with @jboulmal it's now possible to configure this url.

**Comment by jboulmal** [comment]
re-open if needed so

**Comment by emmelmann-fokus** [comment]
@trikolon @endbert -- please confirm that all issues with the nodeJS runtime are resolved. If not, reopen this issue. 

I might have misunderstood some conversations, but up to my knowledge, there were also some issues that the nodeJS runtime API is different from the web browser runtime API which practically means that we lost the "interface independence".
